# Site settings
name: 'Craig Walker'
description: 
meta_description: 
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'cwlogodark.png'
  greetings: "Hello and Welcome."
favicon: 'assets/images/cwsiteicon.png'
baseurl: /roycetest
production_url: https://walkercraig.github.io/roycetest/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form settings
email: mail@walkercraig.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'wlkrcrg'
facebook: 'wlkrcrg'
instagram: 'wlkrcrg'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Letters
    url: /letters/
  . text: Work
    url: /work/
  - text: Organizations
    url: /organizations/
  - text: Creative
    url: /creative/
  - text: Contact
    url: /contact/
  - text: Search
    url: /search/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

remote_theme: royce
